### ISSUE TITLE
Does not seems to work on Android 14

### ISSUE THREAD

**Issue by austinliuu** [mrh929/magisk-wifiadb#12] opened 2024-05-19 00:53 UTC
I have installed the module on Magisk, but wirelss debugging status does not seem to be preserved and I have to manually turn on Wireless debugging after reboot. My device is Pixel Tablet Android 14

**Comment by mrh929** [comment] 2024-05-20 13:49
> I have installed the module on Magisk, but wirelss debugging status does not seem to be preserved and I have to manually turn on Wireless debugging after reboot. My device is Pixel Tablet Android 14 

It seems that WiFi adb in Android 14 requires the client to pair with it before connecting to it, and a random port is used. I'll check it out when I have a test device....

**Comment by austinliuu** [comment] 2024-05-22 02:05
Yeah I have to use a tasker task which it will run commend in Termux to turn on the wireless debugging. Here is the link if you need for reference:
https://taskernet.com/shares/?user=AS35m8lyfRz0LQjeOnogH2mWAtM%2B%2BYGrKyboB3uwK0gLnPDzK0woCq2eOYCXmK8vB3YdObHjDO4%3D&id=Profile%3AEnable+ADB+Wifi+on+Boot

**Comment by mrh929** [comment] 2024-10-27 08:54
> I have installed the module on Magisk, but wirelss debugging status does not seem to be preserved and I have to manually turn on Wireless debugging after reboot. My device is Pixel Tablet Android 14

Hi there! I'm currently working on the bug you mentioned earlier and I have also been able to reproduce the issue. It turns out that this bug is not related to the Android version; rather, the issue lies with the ADB status detection script in the module, which is not functioning correctly. I'll fix it soon. :)

**Comment by mrh929** [comment] 2024-10-27 09:22
please check if this issue is fixed in https://github.com/mrh929/magisk-wifiadb/releases/tag/alpha-1.0.2-07a7c99

**Comment by westruk** [comment] 2024-11-01 06:57
> please check if this issue is fixed in https://github.com/mrh929/magisk-wifiadb/releases/tag/alpha-1.0.2-07a7c99

not work on a15 pixel 6a. need manually turn on Wireless debugging after reboot.

**Comment by vanyasem** [comment] 2024-12-06 09:39
@westruk have you tried connecting to the device by running `adb connect deviceip:5555` ?
The checkbox in the settings will not be active, but remote adb debugging is actually enabled, and does not require pairing
The checkbox in the settings is an entirely separate new way of using adb remotely, and is not affected by this magisk module

@mrh929 I can confirm that the issue is fixed in the latest release running on LineageOS 21 (Android 14) on Samsung Galaxy S8+

**Comment by vanyasem** [comment] 2024-12-06 09:47
@mrh929 btw why has the default maintain availability sleep duration been reduced from 5 seconds to 1?
Is there some particular reason on why 1 second is better than 5?

**Comment by mrh929** [comment] 2024-12-06 10:28
> @mrh929 btw why has the default maintain availability sleep duration been reduced from 5 seconds to 1? Is there some particular reason on why 1 second is better than 5?

no particular reason... maybe it makes the configuration apply more quickly. You can modify the duration in the configuration yourself.

**Comment by mrh929** [comment] 2024-12-06 10:30
> @mrh929 btw why has the default maintain availability sleep duration been reduced from 5 seconds to 1? Is there some particular reason on why 1 second is better than 5?

No particular reason... maybe it makes the adb status more quickly. One day I'll put it in the configuration so that can modify the duration yourself.

**Comment by mrh929** [comment] 2024-12-06 10:34
ooops, I have already written it 

https://github.com/mrh929/magisk-wifiadb/commit/03ca76d1512538b63dfed49d34bbc6874591e24f#diff-0ede375d8e820613a388eb76649bc0de30f09f96b7c65f82b5ab880512e796c6R15

**Comment by vanyasem** [comment] 2024-12-06 14:29
@mrh929 yeah, I've seen the option in the configuration - was wondering if there was some particular reason for the change.
Thanks for the quick response, and for creating this module - it has helped me a lot!

**Comment by westruk** [comment] 2024-12-07 08:02
> @westruk have you tried connecting to the device by running `adb connect deviceip:5555` ? 

worked, thx!

**Comment by vanyasem** [comment] 2024-12-07 10:40
@mrh929 I guess the issue can be closed then?

**Closed as completed** 2024-12-07 13:50 UTC
Labels: bug
